language: scala
scala:
  - 2.13.0
jdk:
  - openjdk8
env:
  - TRAVIS_NODE_VERSION="4"
install:
  - ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install
script:
  - npm test
  - npm run build
  - sbt test
  - sbt package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qvPNTFhVdjwsqwxznvPXvRBrIOnBrlF9LUqu6d+XzuwcV3h+rXepnU9eC424OjYcNqcS/goOP6MnWgVaS91N/mHAxpWwRmhM7d5htWRv8tkbtZyLWqlFy2mOHcmH1Tl04DpzQJ0VU4eIvFODrQFh4xyyE7ZnMdyN8DxybfME2nzV6cdpSwMVDL3zxXfMdQwGAJN5PfYXZ4dR885gmDzFQ8ML8kAN6Y+0xOqWJ6Mk8EXDi5ogWUFSDpdD2BxAywO+q5HT5er/ft28FGJztnRwqT74QL0Z8v/iaT74mttB6X0kxgWFmyryG9w7Wd3dM/PZ76dXYU2u1okFqhvJ6tQRh3pxNPRz+k7d22kdIGQSR7C6KG23nzihKtZMNdL/tnJvGleyd9uch9/Y3ba7po7a/1ZRpj8rzLyvLkSy8MVXTbIkZFsY9zIXtdmgZ0fYmK/ol2K9tJUJoH7zqr8ILRx/HFkBsbnGs+2ClClhQofAw/GJAZg/7PMuSDZXM7fTYpUEiBd8sb/UQ2ZpXZnG1xN2+dNE40Ijkvi34sSomGt4TbJUQ73AwMS+ffcVFo9oe8H93RY95KD5iR7eVSH6TrLg0FefleVmFpMW/OW9SsxV3pH46ngnF1IUFC0gIVVa71hthSTSCd7Ysam0Oom4gaGQcYs1Y2Sh9gh7KtwMwxmMwxo=
  file: target/scala-*/gitbucket-network-plugin*.jar
  file_glob: true
  on:
    tags: true
